name: CI-CD-EKS


on:
  workflow_dispatch: # Se activa manualmente desde GitHub Actions

#on:
#  push:
#    branches:       ## se activa cuando se hace push a la rama main o con git push origin main
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ“¥ Descargar cÃ³digo del repositorio
        uses: actions/checkout@v4

      - name: ğŸ” Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: ğŸ› ï¸ Crear repositorio ECR si no existe
        run: |
          aws ecr describe-repositories --repository-names flask-app --region us-east-1 || aws ecr create-repository --repository-name flask-app --region us-east-1

      - name:  Autenticarse en Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: ğŸ—ï¸ Construir imagen Docker
        run: |
          docker build -t flask-app ./app

      - name: ğŸ“¦ Etiquetar imagen para ECR
        run: |
          docker tag flask-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: ğŸš€ Subir imagen a Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

      - name: ğŸ› ï¸ Crear Backend S3 y DynamoDB para Terraform
        run: |
          aws s3api head-bucket --bucket project03-terraform-state12345 2>/dev/null || aws s3api create-bucket --bucket project03-terraform-state12345 --region us-east-1
          aws dynamodb describe-table --table-name project03-terraform-lock --region us-east-1 2>/dev/null || aws dynamodb create-table --table-name project03-terraform-lock --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --region us-east-1

      - name:  Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: ğŸ—ï¸ Inicializar Terraform
        run: terraform init
        working-directory: ./terraform

      - name: ğŸš€ Aplicar Terraform (Crear Cluster y Esperar)
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: ï¿½ Actualizar kubeconfig para conectarse a EKS
        run: aws eks update-kubeconfig --name project03-eks

      - name: ğŸ”§ Reemplazar ID de cuenta en manifiestos
        run: sed -i "s|<ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|g" k8s/*.yaml

      - name: ï¿½ Desplegar aplicaciÃ³n en EKS
        run: kubectl apply -f k8s/
